### ISSUE TITLE
Can I customize the title

### ISSUE THREAD

**Issue by qinjianwei** [KevinSilvester/wezterm-config#24]
I will create many tabs, and sometimes I can't tell which one corresponds to which. I want to customize the title to distinguish it. Can you tell me what I should do?

**Comment by KevinSilvester** [comment]
it is possible with a key binding similar to [this](https://wezfurlong.org/wezterm/config/lua/keyassignment/PromptInputLine.html?h=prom#example-of-interactively-renaming-the-current-tab)

```lua
  {
    key = 'E',
    mods = 'CTRL|SHIFT',
    action = act.PromptInputLine {
      description = 'Enter new name for tab',
      initial_value = 'My Tab Name',
      action = wezterm.action_callback(function(window, pane, line)
        -- line will be `nil` if they hit escape without entering anything
        -- An empty string if they just hit enter
        -- Or the actual line of text they wrote
        if line then
          window:active_tab():set_title(line)
        end
      end),
    },
  }
```

The only problem is that the `tab-title` event will keep overwriting the new name.

It can be done but I'd say it requires some tweeking to tab-title event so that freezes the title if it's been manually updated.

Working on something for rn
I'll let you know if I get it working

**Comment by qinjianwei** [comment]
Thank you for your answer. Looking forward to the completion of this feature

**Comment by KevinSilvester** [comment]
Tab titles are now editable with the key bindings '<kbd>LEADER</kbd>+<kbd>0</kbd>' and "un-renamed" with '<kbd>LEADER_REV</kbd>+<kbd>0</kbd>'

https://github.com/KevinSilvester/wezterm-config/blob/f9e38bd8cd5446e7a59590947f8e4b17e664d33a/config/bindings.lua#L72-L75

**Comment by qinjianwei** [comment]
Thank you, the experience of this feature is fantastic
