### ISSUE TITLE
`BackDrops:set_files` loading `.DS_Store` as image file (blank background)

### ISSUE THREAD

**Issue by username-adk** [KevinSilvester/wezterm-config#25]
Once I've deleted two or more backgrounds from the backgrounds folder, I get a bland background added to the cycle. So, as I cycle to the next image, I get the normal backgrounds in the folder but then an additional blank one. It's as if there is a blank background image in the folder.

This happens on a fresh install of the configuration too. If I put the deleted backgrounds back that doesn't get rid of the problem. I can add images to the background folder just fine, but once I've deleted two or more then the blank shows up. 

To get the backgrounds I wanted I had to create a new empty backdrop folder and then add the images in.

**Comment by KevinSilvester** [comment]
Hey @username-adk, I've been trying to reproduce the issue for a while now with no luck.
Could you tell me which OS and version of wezterm you're running? 

```sh
wezterm --version
```

**Comment by username-adk** [comment]
wezterm 20240203-110809-5046fc22
macOS 15.0.1 (24A348)

I only noticed this problem after updating to Sequoia 15.0.1 but I don't know if I just missed it before.

I tried to recreate the problem again and it's still there.
- Backed up .config/wezterm then deleted it.
- Deleted the folder in .local/share.
- Brew uninstall wezterm.
- Brew install wezterm.
- Git clone your repo.
- Opened up wezterm and the backgrounds work fine.
- Closed it, deleted one pic from .config/wezterm/backdrops, opened it again and the backgrounds work 
   fine (with deleted one not showing up).
- Did the same with a second pic and now a blank background shows up.

I think what really throws me is that if I put the deleted pics back the problem persists. 

Anyway my normal config doesn't have this problem. I love yours so it's just a copy with a couple changes.
I fixed it by adding an empty backdrops folder and then only adding the images I wanted.

**Comment by KevinSilvester** [comment]
From what you've described, what I think is happening is somehow the `BackDrops:set_files()` is finding files that aren't supposed to exist in the `backdrops` directory?

Cuz I was able to replicate the blank background image while cycling, but only after I hard-coded a file path to an image that doesn't exist:
```lua
function BackDrops:set_files()
   self.files = wezterm.read_dir(wezterm.config_dir .. PATH_SEP .. 'backdrops')
   table.insert(self.files, 'C:\\Users\\kevin\\.config\\wezterm\\backdrops\\i-dont-exist.jpg')
   wezterm.GLOBAL.background = self.files[1]
   return self
end
```


So what I'm wondering now is how you deleted the files.
Did you use the command line to `rm image.jpg` or did you use Finder?

This is just a guess on my part, but if you did use Finder and you're getting this issue, I think what may have happened is in the OS update you just got, the way Finder handles deleting files may have changed (maybe for restoring deleted items?).
If so, try deleting the image you no longer want in the command line.

On the other hand, if you did use the command line and are getting the issue, I am stumped.
Not a clue how this happened.

That being said, it might still be worth checking out the nightly build, since this might be an issue that is already patched.
```sh
brew install --cask wezterm@nightly
```

You could also check if `BackDrops:set_files` really is finding non-existent files by:
1. Press <kbd>F12</kbd> to enter debug mode
2. Paste the following line in the debugger to dump the current `BackDrops` state
    ```lua
    require('utils.backdrops').files
    ```
    You should get something like this:
    <img width="491" alt="image" src="https://github.com/user-attachments/assets/165e13ae-f957-415a-b617-ec8bdc01f8b6">

If neither the nightly version nor deleting with the command line don't work, it might be worth filing an issue to wezterm.

**Comment by username-adk** [comment]
You've got it! Deleting using the command line doesn't raise this issue.

Following your debug mode steps I got:
> require('utils.backdrops').files

[
    "/Users/anthony/.config/wezterm/backdrops/.DS_Store",
    "/Users/anthony/.config/wezterm/backdrops/final-showdown.jpg",
    "/Users/anthony/.config/wezterm/backdrops/pastel-samurai.jpg",
    "/Users/anthony/.config/wezterm/backdrops/frieren.jpeg",
]

So it looks like .DS_Store is being picked up as an additional background.

**Comment by KevinSilvester** [comment]
Nice!

I forgot that `.DS_Store` has a tendency to slip into some unwanted places 😂.
I'll switch over to `wezterm.glob` instead of `read_dir` to load only the supported image files instead so you won't have to keep deleting the file.

Thanks for finding the bug 😎

**Comment by username-adk** [comment]
And thanks for your config!

wezterm.glob worked nicely. In BackDrops:set_files
I just changed the line:
>   self.files = wezterm.read_dir(wezterm.config_dir .. PATH_SEP .. 'backdrops')

to
>   self.files = wezterm.glob(wezterm.config_dir .. PATH_SEP .. 'backdrops/*')

and now I can remove backgrounds without any issues.

**Comment by KevinSilvester** [comment]
> And thanks for your config!
> 
> wezterm.glob worked nicely. In BackDrops:set_files I just changed the line:
> 
> > self.files = wezterm.read_dir(wezterm.config_dir .. PATH_SEP .. 'backdrops')
> 
> to
> 
> > self.files = wezterm.glob(wezterm.config_dir .. PATH_SEP .. 'backdrops/*')
> 
> and now I can remove backgrounds without any issues.

Nice!

You might want to add the glob pattern to only select the supported image files though:
```lua
self.files = wezterm.glob(wezterm.config_dir .. PATH_SEP .. 'backdrops/*.{jpg,jpeg,png,gif,bmp,ico,tiff,pnm,dds,tga}')
```
