### ISSUE TITLE
how to increase the size of the terminal window?

### ISSUE THREAD

**Issue by zaeboba** [KevinSilvester/wezterm-config#30]
Hi, I am not a programmer and I do not understand where is the file that is responsible for the size of the window, I go into the font, change the font and increase the size of the window, but I do not need to change the size of the font, I just need to increase the size of the window/.
I would also like the window to appear exactly in the middle of the screen.
![изображение](https://github.com/user-attachments/assets/8a5b86fb-d2e9-40d0-8d7c-dce0c2470d3e)

**Comment by KevinSilvester** [comment]
Hey @zaeboba, I'm unsure if either feature is possible in WezTerm.

Zooming in without changing the font size is possible, but I'm not sure how to do it usefully. 
The [`Window`](https://wezfurlong.org/wezterm/config/lua/window/index.html) object in wezterm has two methods for get and setting the window size, [`set_inner_size`](https://wezfurlong.org/wezterm/config/lua/window/set_inner_size.html) and [`get_dimensions`](https://wezfurlong.org/wezterm/config/lua/window/get_dimensions.html). 
The issue is that `get_dimensions` returns the current window's size in pixels while `set_inner_size` uses the text character width as its unit of measurement. Without converting one unit to the other I'm not sure how to go about incrementing or decrementing the current window size.
You can however zoom the window to a hardcoded size but this probably isn't what you're looking for:
```lua
   -- window: zoom window
   { key = '-',          mods = mod.SUPER,     action = wezterm.action_callback(function(window, _pane)
      window:set_inner_width(300, 300)
   end) },
```


It's a similar story with centring the window since the [`Window`](https://wezfurlong.org/wezterm/config/lua/window/index.html) object does have the method [`set_position`](https://wezfurlong.org/wezterm/config/lua/window/set_position.html), but I don't think WezTerm has a way to get the screen size to calculate the pixel coordinates to centre the terminal window.

**Comment by zaeboba** [comment]
Okay, what file do I put it in?

**Comment by KevinSilvester** [comment]
`config/bindings.lua`

**Comment by zaeboba** [comment]
the console is breaking.
Something must be wrong.
![изображение](https://github.com/user-attachments/assets/4debe410-6d09-4828-82a5-a66a296cb536)

**Comment by KevinSilvester** [comment]
make sure the new binding is in the [`keys`](https://github.com/KevinSilvester/wezterm-config/blob/4d3ff4de8e5612b30dc7654b64df31ceac332864/config/bindings.lua#L17) table:

<img width="712" alt="image" src="https://github.com/user-attachments/assets/e36a774e-04dc-40a2-a4de-2f7c5e56bd68">

**Comment by zaeboba** [comment]
![изображение](https://github.com/user-attachments/assets/32d75ca9-b87d-4498-9187-57fb912fe281)
the window won't enlarge.
is it sure it should work on windows?

**Comment by KevinSilvester** [comment]
> the window won't enlarge.
> is it sure it should work on windows?

I made a mistake in the example, it should've been `set_inner_size` not `set_inner_width`.

Also, I misread the docs.
Pixels seem the units for the `set_inner_size` method
Try these keybindings. They should let you increase and decrease the window sizes

```lua
   -- window: zoom window
   {
      key = '-',
      mods = mod.SUPER,
      action = wezterm.action_callback(function(window, _pane)
         local dimensions = window:get_dimensions()
         if dimensions.is_full_screen then
            return
         end
         local new_width = dimensions.pixel_width - 50
         local new_height = dimensions.pixel_height - 50
         window:set_inner_size(new_width, new_height)
      end)
   },
   {
      key = '=',
      mods = mod.SUPER,
      action = wezterm.action_callback(function(window, _pane)
         local dimensions = window:get_dimensions()
         if dimensions.is_full_screen then
            return
         end
         local new_width = dimensions.pixel_width + 50
         local new_height = dimensions.pixel_height + 50
         window:set_inner_size(new_width, new_height)
      end)
   },
```

**Comment by zaeboba** [comment]
yes, it works, but it doesn't remember the enlarged window, every time you start up you have to enlarge it(

**Comment by tobi187** [comment]
Hei @zaeboba ,
if it helps you, i did it by specifing the rows and cols in the config/appeareance.lua (although don't think the file matters)
![image](https://github.com/user-attachments/assets/a1db59d7-b596-4e4c-ab62-3a72f7be493f)
This works (at least for me) for setting the inital window size :D

**Comment by zaeboba** [comment]
> Hei @zaeboba , if it helps you, i did it by specifing the rows and cols in the config/appeareance.lua (although don't think the file matters) ![image](https://private-user-images.githubusercontent.com/61592216/381248745-a1db59d7-b596-4e4c-ab62-3a72f7be493f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjU0MTUsIm5iZiI6MTczMDIyNTExNSwicGF0aCI6Ii82MTU5MjIxNi8zODEyNDg3NDUtYTFkYjU5ZDctYjU5Ni00ZTRjLWFiNjItM2E3MmY3YmU0OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDkxOGUwYzk2ZmY3N2NhMTBkM2ZmMGY0YzM5ZGJkODJiODE1OTMzZjliNWQ1ZDExNGJjMGQ2ZTQ2OTg0N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.60D6Bf6esZYW7IckNK3x6xl1cxRHcc92p4VdKkRM26o) This works (at least for me) for setting the inital window size :D

![изображение](https://github.com/user-attachments/assets/353d1097-8e1f-449c-805c-5e463326ae01)
I'm not a programmer, and I don't understand how to write it correctly so I don't break it.
