### ISSUE TITLE
not operated for a long time, the wezterm will get stuck and unresponsive

### ISSUE THREAD

**Issue by qinjianwei** [KevinSilvester/wezterm-config#36]
If not operated for a long time, the wezterm will get stuck and unresponsive。I don't know if it's related to your configuration

**Comment by KevinSilvester** [comment]
Maybe I'm wrong, but I don't think it's related to my config.

I regularly leave Wezterm running on my laptop while I go for lunch/break/meeting etc. and I don't think it's ever been unresponsive when I return to work.

Granted, I usually have an app running in the foreground like Neovim or some other long-running task like re-encoding a video with ffmpeg when I do leave Wezterm running idle, so I'm not sure if that's why I've never encountered this problem.

It might be worthwhile checking the issues tab in the [wezterm repo](https://github.com/wez/wezterm) to see if this is a known issue.

**Comment by qinjianwei** [comment]
okay, thank you
