### ISSUE TITLE
Features req (activity & custom settings)

### ISSUE THREAD

**Issue by damajor** [KevinSilvester/wezterm-config#38]
First this config is great congratz :)

Regarding unseen activity, it is working great if the tab has no pane. If the tab has panes, only the active pane raises activity icon. I think it would be great to have unseen activity also from non focused pane.

Regarding the custom settings:
- maybe having the datetime format as custom setting would be a good idea (in appearance config file for eg)
- more config dedicated to visual_bell (also in appearance config file)
- size controls of fonts & panes are great, background should follow same logic I think with leader key
- custom backdrops location

**Comment by KevinSilvester** [comment]
Hey @damajor,

Thanks for the great feedback.

So far, I've added the `visual_bell` option to `config/appearance.lua`, fixed the unseen_output issue, and added an option to the `Backdrops` util to set a custom directory for the images.

I think I'll keep the datetime format setting in the `right-status` event file as I want all the items in the `config` dir to be configuration options for WezTerm only.

Also, making the background controls into a `key_table` works to a degree, but isn't very fun to use.
The background control bindings are custom actions wrapped in an [`action_callback`](https://wezfurlong.org/wezterm/config/lua/wezterm/action_callback.html) and for some reason, action_callbacks, seem to exit the key table as soon as they are completed rather than staying in the key_table.
This makes basic actions like cycling through the images a pain because you'll have to do the whole key sequence to activate the key_table every time.

So, for now, I'll keep the background controls as is.

**Comment by damajor** [comment]
> Also, making the background controls into a `key_table` works to a degree, but isn't very fun to use.
> The background control bindings are custom actions wrapped in an [`action_callback`](https://wezfurlong.org/wezterm/config/lua/wezterm/action_callback.html) and for some reason, action_callbacks, seem to exit the key table as soon as they are completed rather than staying in the key_table.
> This makes basic actions like cycling through the images a pain because you'll have to do the whole key sequence to activate the key_table every time.

I did it myself this way and I found the exact same behavior, a bit frustrated :)

And of course thanks for the updates.

**Comment by KevinSilvester** [comment]
No worries 😊

**Comment by damajor** [comment]
Hmm the unseen activity seems to be a step forward the perfect resolution :p

I noticed that when you are in a tab with multiple panes, the panes with activity that are NOT focused generate the activity icon. I would expect this behavior on NOT focused tabs, but not on the tab that is currently in use.

This is not a big deal btw :)

**Comment by KevinSilvester** [comment]
`unseen_ouptut` alert no longer shows for any of panes of the active tab

**Comment by damajor** [comment]
I think it can be a be more polished but it is working great now.

Well this is going complicated :D 

2 Tabs
1rst tab shell only
2d tab with 3 panes (one active with top, the 2 others only shell)

Test 1:
- 2d tab, pane with top has focus
- Wait top refresh and go to first tab
- unseen icon should appear in few second (the time top refresh)
This is working fine.

Test 2:
- 2d tab, pane with top WITHOUT focus, so put focus on any other pane in the same tab
- Wait top refresh and go to first tab
- unseen icon appears instantly you leave the tab with panes
Behavior expected is to be notified only until when real activity occurs

**Comment by damajor** [comment]
Agreed :)

**Comment by KevinSilvester** [comment]
Just pushed a change that makes the date time format configurable in the event setup function.

https://github.com/KevinSilvester/wezterm-config/blob/6febb08f74a2d0a0975cd330787d0f1dab2b8fac/wezterm.lua#L8-L13
