### ISSUE TITLE
unseen activity reset when switching to fullscreen (F11)

### ISSUE THREAD

**Issue by damajor** [KevinSilvester/wezterm-config#39]
As title says the unseen activity circle appears always on every tabs each time you press F11.

**Comment by KevinSilvester** [comment]
This appears to be a bug caused by the way WezTerm's pane state checks for unseen output rather than a bug caused by the config.
I've noticed resizing the application window in any manner triggers the `has_unseen_output` to be set to `true` and can't really think of any workarounds for this.

Might be worth filing an issue in the wezterm repo.

**Comment by damajor** [comment]
Close as not related to config but main wezterm behavior.
